### ISSUE TITLE
grails 3.1.6 can not use this plugin

### ISSUE THREAD

**Issue by 112921482** [budjb/http-requests#1]
when I compile 'com.budjb:http-requests-grails:0.1.7.BETA' in my project with grails 3.1.6, I can't run my project and throw exception java.lang.IllegalStateException: no provider with type 'com.budjb.httprequests.HttpClientFactory' found on the classpath, can you help me?

**Comment by budjb** [comment]
Sure! You're missing an implementation JAR. The Grails plugin doesn't choose the implementation for you. All it does it scan the classpath for one, and loads it as a managed Spring Bean that you can inject. You can do one of 2 things to make this work:
- Add the implementation artifact directly as a project dependency. You can use **http-requests-jersey1**, **http-requests-jersey2**, or **http-requests-httpcomponents-client**.
- Use the BOM to keep versions in sync. See the example below from the [documentation](https://budjb.github.io/http-requests/latest/).

``` groovy
dependencyManagement {
    imports {
        mavenBom "org.grails:grails-bom:$grailsVersion"
        mavenBom "com.budjb:http-requests:0.1.7.BETA"
    }
    applyMavenExclusions false
}

dependencies {
    // ...
    compile "com.budjb:http-requests-grails"
    compile "com.budjb:http-requests-jersey1"
}
```

**Comment by 112921482** [comment]
Thanks very much.
