### ISSUE TITLE
contentType.substring error

### ISSUE THREAD

**Issue by 112921482** [budjb/http-requests#2]
there is an error caused by 'contentType.substring(0, contentType.indexOf(';'))' 
when clientResponse content type is 'text/plain' in JerseyHttpClient.groovy line 146.
what should I do or you will fix this as a bug?

**Comment by budjb** [comment]
This is a bug. I'll have it fixed with 0.1.12.BETA shortly.

**Comment by budjb** [comment]
0.1.12.BETA has been released.
