### ISSUE TITLE
encoding error when post

### ISSUE THREAD

**Issue by 112921482** [budjb/http-requests#4]
if I post a input stream which contains Chinese characters will response correct, but I get an error like this ""errmsg" -> "invalid charset. please check your request, if include \uxxxx will create fail! hint: [3VS4na0952vr18]"" when I post the same thing with json request. I try to set charset to utf-8, but it didn't work.

**Comment by budjb** [comment]
Do you have some example code that reproduces this?

**Comment by budjb** [comment]
I never received a response to the question above, so closing the issue. If this is still a problem, please re-open it with an example and I'll gladly take a look. Thanks!
