### ISSUE TITLE
Support for posting XML content

### ISSUE THREAD

**Issue by thecodesmith** [budjb/http-requests#6]
I'm working with a couple legacy APIs that only support XML for POST Content-Type. Looking through the code I see that `http-requests` only supports the `XmlSlurperEntityReader`, but not its `...Writer` compatriot.

Are you planning to support posting XML?

**Comment by budjb** [comment]
What object do you want to pass that contains XML? I didn't add a built-in because the groovy markup builders are mostly aimed at writing to a `StringWriter`.

**Comment by thecodesmith** [comment]
Ah, you mean use a markup builder to create an XML string, and use that as the request content? That sounds reasonable, I'll try it out.

Ideally I'd like to be able to post a Map directly and specify an XML content-type, like is possible with JSON. It would only be simple nested data, no XML attributes. Do you think that is worthwhile, or should we stick with a markup builder solution?

**Comment by budjb** [comment]
The library is a bit opinionated right now if you use the default set of converters in that it always tries to treat lists or maps like JSON. Now that you mention your use case, this might be an area that could be improved.

The thing about map/list structures is that they have a 1-1 conversion to and from JSON, but this not the case with XML (and lists, in particular). If an XML renderer is outputting XML based on a list  in a generic fashion, it is making decisions about your schema for you. This reason gives me pause about having a generic, automatic conversion **to** XML.

**Comment by thecodesmith** [comment]
I got my case working and based on your explanation, I think this can be closed. Thanks!
