### ISSUE TITLE
AuthenticationTokenHeaderFilter example

### ISSUE THREAD

**Issue by thecodesmith** [budjb/http-requests#8]
Hi, @budjb, thanks so much for the excellent library. I'm using it quite a bit.

I read the docs, source code and tests, but I'm still having trouble understanding how to implement an `AuthenticationTokenHeaderFilter`. What would the `authenticate()` method look like if my auth endpoint is http://my.api/auth? Does it need to do a full request/response to get the auth token inside the method?

**Comment by budjb** [comment]
The `authenticate` method just does whatever it needs to do to get a valid authentication token, and then sets it with `setAuthenticationToken()`.

Below is a basic example of an authentication filter that requires an `HttpClientFactory` to make the authentication request. You might also pass a class that contains the logic to authenticate.

```
class ExampleAuthFilter extends AuthenticationTokenHeaderFilter {
    HttpClientFactory factory

    ExampleAuthFilter(HttpClientFactory factory) {
        this.factory = factory
    }

    /**
     * This authentication method makes a call to the example URL with a JSON payload
     * containing a username and password, and assume the response entity is the string
     * authentication token.
     */
    @Override
    protected void authenticate() {
        HttpClient client = factory.createHttpClient().clearFilters()

        // make an actual request
        HttpResponse response = client.post([username: 'foo', password: 'bar']) {
            uri = 'http://my.api/auth'
        }

        setAuthenticationToken(response.getEntity(String))
    }

    /**
     * This method tells the client using this filter to create a header with the name
     * <pre>X-Authentication-Token</pre> and the value returned from
     * {@link #getAuthenticationToken}.
     */
    @Override
    protected String getAuthenticationTokenHeader() {
        return 'X-Authentication-Token'
    }
}
```

**Comment by thecodesmith** [comment]
Perfect, thank you very much! I was trying to see how I could reuse the existing `HttpClient` instance, but this makes sense that the filter maintains its own.

**Comment by budjb** [comment]
You most certainly can use the same http client instance if you'd like. The filter does not impose any assumptions about how to authenticate, so you can provide your filter whatever you need to make an authentication attempt. I chose an `HttpClientFactory` in this example, but most of the time I actually use a service class to do this kind of thing (and pass the singleton Spring bean instance of it to the filter).

I think the reason to not use an existing client (and especially the one used to make the initial request) is that this filter shouldn't modify the client in any way, ideally. The client contains a set of filters and converters. The client would contain this auth filter, so if you reused the same client and your authentication attempt fails, you'd end up with potentially an unbounded loop.
